
FROM node:22-bookworm-slim

WORKDIR /app

RUN apt-get update && apt-get install -y python3 make g++ postgresql-client

COPY package*.json ./
RUN npm install

COPY prisma/schema.prisma prisma/schema.prisma
RUN npx prisma generate

COPY . .

EXPOSE 3000

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]
